# Header

menu:
  主页: /
  归档: /archives

  #个人: /tags/个人/

  #个人: /categories/个人/
  #技术: /categories/技术/
  #专利: /categories/专利/
  #创新: /categories/创新/
  #管理: /categories/管理/
  
# SubNav
subnav:
  github: "https://github.com/ipcreator"
  weibo: "http://weibo.com/zhuxuanlvzxl/home?wvr=5&lf=reg"
  zhihu: "https://www.zhihu.com/people/AndyWang18/activities"
  douban: "https://www.douban.com/people/1390598/"
  #mail: "mailto:ipcreator@yeah.net"
  rss: /atom.xml
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"
  #rss: "#"

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: '谢谢您的打赏！'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: http://okkntqe2h.bkt.clouddn.com/alipay_cr.jpg
# 微信二维码图片地址
weixin: 

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
#favicon: /favicon.png

favicon: /img/personalphoto.jpg

#你的头像url
avatar: /img/personalphoto.jpg
#avatar: http://okkntqe2h.bkt.clouddn.com/personalphoto.jpg

#是否开启分享
share_jia: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
duoshuo-key: ipcreator

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  你的生命有什么可能: https://book.douban.com/subject/25870384/
  个体崛起的时代: http://mt.sohu.com/20161026/n471374646.shtml
  成为一个超级个体: http://blog.sina.com.cn/s/blog_4b09eac00102wnfy.html
  人工智能的黄金时代: http://gelonghui.com/p/101767.html
  人人都是工程师: http://lixiaolai.com/2016/06/12/makecs-preface/
  人人都能用英语: http://zhibimo.com/read/xiaolai/everyone-can-use-english/  
  把时间当作朋友: http://zhibimo.com/read/xiaolai/ba-shi-jian-dang-zuo-peng-you/index.html
  七年就是一辈子: http://zhibimo.com/read/xiaolai/reborn-every-7-years/
  退休感言: http://news.mbalib.com/story/12504
  选择的智慧: http://www.360doc.com/content/14/1206/17/15680008_430856157.shtml  
  此生未完成: https://book.douban.com/subject/6397275/
  向死而生: https://book.douban.com/subject/26422275/


#展示图片
fancybox: true

#标签云
tagcloud: true

swift_search:
  enable: true



aboutme: 自知者明<br>自胜者强<br>不忘初心<br>方得始终